name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: hmcts/cnp-azuredevops-libraries
          path: cnp-azuredevops-libraries

      - name: Setup Script
        run: |
          chmod +x cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
      - name: Setup Terraform
        run: ./cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
        working-directory: ./
        shell: bash

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: terraform_fmt --all-files
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: environments/* components/* modules/*
